language: rust
dist: xenial

rust:
  - stable

os:
  - linux
  - osx
  - windows

addons:

  homebrew:
    packages:
      - python

install:
  - bash ci/install.sh

script:
  - bash ci/check.sh

before_deploy:
  - bash ci/gen_artifacts.sh

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: uSrVFvV6h5/5T7oaoXNu0rhoELqpeDxLQeE6sIPe0roA0OrsUuegLVP6IIcGg5bm0Ce7A31i7iFUqlXkZUDVRAn06d1wBFz3d7B2SXoLUREZwVj75woBYkTZFmDEQekV/uUAPSOLToToGPpXuASeGh2lNB1J86cBsKTilPcQMOjJu+s9y6/g3PdxgQZ1Th38IR1D+GqDrxAjdlhHGDMQg46EaG/NWqC1dr3jNztXR/L3ee8uyfZCVViIKxrtltDL40VcrjPcFa08yzIuwjVZkEwFRobBy8vX3bn5eIVCaauQPZWznIpgP+T6/hmiLEt2IuksQouoKrGTmQAG9vvBo9bFsAxr3optyOIyr8gssUrgrE0Xh+ONsPJtkqTZonXH5VXGGXirQlOoPCiLsLzjWAqBLAaVGHHisMNd0sMQ2JWfiP06AWs8n0hKsW9TATn05bDkSG1sXE1T+ZMdyYVz1bOSWr4+mYp8uYVVeDRzsPKuqH12Z8dZDLwtFGvG7ZmlMGm3XBvWJacbO/qgIPc+w7Prq6Asu28SA5BOC3jxJPGdhgP0Fi6Cd6O4AKHGETXda+HgEU1Ul4BYVY9PVdyFKjU/fZeHRTNham/ZVd4HEU9ibJ3TGSqCv+r8jIuCYMFF/cEI5Yp3aJtRQcXTsDn+e5BmdDTE9IUXV5ddXkOtA20=
  file_glob: true
  file:
    - dist/*
  on:
    repo: TankerHQ/dmenv
    tags: true
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
